// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

public class AuthDto {

    public static class EmailRequest {
        @NotBlank
        @Email
        private String email;
        private String name; // optional, used for first-time registration

        @java.lang.SuppressWarnings("all")
        
        public EmailRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public String getEmail() {
            return this.email;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setEmail(final String email) {
            this.email = email;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AuthDto.EmailRequest)) return false;
            final AuthDto.EmailRequest other = (AuthDto.EmailRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$email = this.getEmail();
            final java.lang.Object other$email = other.getEmail();
            if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AuthDto.EmailRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $email = this.getEmail();
            result = result * PRIME + ($email == null ? 43 : $email.hashCode());
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "AuthDto.EmailRequest(email=" + this.getEmail() + ", name=" + this.getName() + ")";
        }
    }


    public static class OtpVerifyRequest {
        @NotBlank
        @Email
        private String email;
        @NotBlank
        private String otp;

        @java.lang.SuppressWarnings("all")
        
        public OtpVerifyRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public String getEmail() {
            return this.email;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getOtp() {
            return this.otp;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setEmail(final String email) {
            this.email = email;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setOtp(final String otp) {
            this.otp = otp;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AuthDto.OtpVerifyRequest)) return false;
            final AuthDto.OtpVerifyRequest other = (AuthDto.OtpVerifyRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$email = this.getEmail();
            final java.lang.Object other$email = other.getEmail();
            if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
            final java.lang.Object this$otp = this.getOtp();
            final java.lang.Object other$otp = other.getOtp();
            if (this$otp == null ? other$otp != null : !this$otp.equals(other$otp)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AuthDto.OtpVerifyRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $email = this.getEmail();
            result = result * PRIME + ($email == null ? 43 : $email.hashCode());
            final java.lang.Object $otp = this.getOtp();
            result = result * PRIME + ($otp == null ? 43 : $otp.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "AuthDto.OtpVerifyRequest(email=" + this.getEmail() + ", otp=" + this.getOtp() + ")";
        }
    }


    public static class AuthResponse {
        private String token;
        private String tokenType = "Bearer";
        private UserDto.UserProfileDto user;

        public AuthResponse(String token, UserDto.UserProfileDto user) {
            this.token = token;
            this.user = user;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getToken() {
            return this.token;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getTokenType() {
            return this.tokenType;
        }

        @java.lang.SuppressWarnings("all")
        
        public UserDto.UserProfileDto getUser() {
            return this.user;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setToken(final String token) {
            this.token = token;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setTokenType(final String tokenType) {
            this.tokenType = tokenType;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setUser(final UserDto.UserProfileDto user) {
            this.user = user;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof AuthDto.AuthResponse)) return false;
            final AuthDto.AuthResponse other = (AuthDto.AuthResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$token = this.getToken();
            final java.lang.Object other$token = other.getToken();
            if (this$token == null ? other$token != null : !this$token.equals(other$token)) return false;
            final java.lang.Object this$tokenType = this.getTokenType();
            final java.lang.Object other$tokenType = other.getTokenType();
            if (this$tokenType == null ? other$tokenType != null : !this$tokenType.equals(other$tokenType)) return false;
            final java.lang.Object this$user = this.getUser();
            final java.lang.Object other$user = other.getUser();
            if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof AuthDto.AuthResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $token = this.getToken();
            result = result * PRIME + ($token == null ? 43 : $token.hashCode());
            final java.lang.Object $tokenType = this.getTokenType();
            result = result * PRIME + ($tokenType == null ? 43 : $tokenType.hashCode());
            final java.lang.Object $user = this.getUser();
            result = result * PRIME + ($user == null ? 43 : $user.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "AuthDto.AuthResponse(token=" + this.getToken() + ", tokenType=" + this.getTokenType() + ", user=" + this.getUser() + ")";
        }
    }
}
