// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.dto;

import com.example.demo.entity.Conversation;
import com.example.demo.entity.Message;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

public class MessageDto {

    public static class SendMessageRequest {
        @NotNull
        private Long receiverId;
        @NotBlank
        private String content;

        @java.lang.SuppressWarnings("all")
        
        public SendMessageRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getReceiverId() {
            return this.receiverId;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getContent() {
            return this.content;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setReceiverId(final Long receiverId) {
            this.receiverId = receiverId;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setContent(final String content) {
            this.content = content;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof MessageDto.SendMessageRequest)) return false;
            final MessageDto.SendMessageRequest other = (MessageDto.SendMessageRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$receiverId = this.getReceiverId();
            final java.lang.Object other$receiverId = other.getReceiverId();
            if (this$receiverId == null ? other$receiverId != null : !this$receiverId.equals(other$receiverId)) return false;
            final java.lang.Object this$content = this.getContent();
            final java.lang.Object other$content = other.getContent();
            if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof MessageDto.SendMessageRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $receiverId = this.getReceiverId();
            result = result * PRIME + ($receiverId == null ? 43 : $receiverId.hashCode());
            final java.lang.Object $content = this.getContent();
            result = result * PRIME + ($content == null ? 43 : $content.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "MessageDto.SendMessageRequest(receiverId=" + this.getReceiverId() + ", content=" + this.getContent() + ")";
        }
    }


    public static class MessageResponse {
        private Long id;
        private Long conversationId;
        private UserDto.UserProfileDto sender;
        private String content;
        private boolean read;
        private LocalDateTime createdAt;

        public static MessageResponse from(Message message) {
            MessageResponse dto = new MessageResponse();
            dto.setId(message.getId());
            dto.setConversationId(message.getConversation().getId());
            dto.setSender(UserDto.UserProfileDto.from(message.getSender()));
            dto.setContent(message.getContent());
            dto.setRead(message.isRead());
            dto.setCreatedAt(message.getCreatedAt());
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public MessageResponse() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getConversationId() {
            return this.conversationId;
        }

        @java.lang.SuppressWarnings("all")
        
        public UserDto.UserProfileDto getSender() {
            return this.sender;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getContent() {
            return this.content;
        }

        @java.lang.SuppressWarnings("all")
        
        public boolean isRead() {
            return this.read;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setConversationId(final Long conversationId) {
            this.conversationId = conversationId;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setSender(final UserDto.UserProfileDto sender) {
            this.sender = sender;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setContent(final String content) {
            this.content = content;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setRead(final boolean read) {
            this.read = read;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCreatedAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof MessageDto.MessageResponse)) return false;
            final MessageDto.MessageResponse other = (MessageDto.MessageResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.isRead() != other.isRead()) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$conversationId = this.getConversationId();
            final java.lang.Object other$conversationId = other.getConversationId();
            if (this$conversationId == null ? other$conversationId != null : !this$conversationId.equals(other$conversationId)) return false;
            final java.lang.Object this$sender = this.getSender();
            final java.lang.Object other$sender = other.getSender();
            if (this$sender == null ? other$sender != null : !this$sender.equals(other$sender)) return false;
            final java.lang.Object this$content = this.getContent();
            final java.lang.Object other$content = other.getContent();
            if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof MessageDto.MessageResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + (this.isRead() ? 79 : 97);
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $conversationId = this.getConversationId();
            result = result * PRIME + ($conversationId == null ? 43 : $conversationId.hashCode());
            final java.lang.Object $sender = this.getSender();
            result = result * PRIME + ($sender == null ? 43 : $sender.hashCode());
            final java.lang.Object $content = this.getContent();
            result = result * PRIME + ($content == null ? 43 : $content.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "MessageDto.MessageResponse(id=" + this.getId() + ", conversationId=" + this.getConversationId() + ", sender=" + this.getSender() + ", content=" + this.getContent() + ", read=" + this.isRead() + ", createdAt=" + this.getCreatedAt() + ")";
        }
    }


    public static class ConversationResponse {
        private Long id;
        private List<UserDto.UserProfileDto> participants;
        private String lastMessage;
        private LocalDateTime lastMessageAt;
        private long unreadCount;

        public static ConversationResponse from(Conversation conversation, long unreadCount) {
            ConversationResponse dto = new ConversationResponse();
            dto.setId(conversation.getId());
            dto.setParticipants(conversation.getParticipants().stream().map(UserDto.UserProfileDto::from).collect(Collectors.toList()));
            dto.setLastMessage(conversation.getLastMessage());
            dto.setLastMessageAt(conversation.getLastMessageAt());
            dto.setUnreadCount(unreadCount);
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public ConversationResponse() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public List<UserDto.UserProfileDto> getParticipants() {
            return this.participants;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getLastMessage() {
            return this.lastMessage;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getLastMessageAt() {
            return this.lastMessageAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public long getUnreadCount() {
            return this.unreadCount;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setParticipants(final List<UserDto.UserProfileDto> participants) {
            this.participants = participants;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLastMessage(final String lastMessage) {
            this.lastMessage = lastMessage;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLastMessageAt(final LocalDateTime lastMessageAt) {
            this.lastMessageAt = lastMessageAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setUnreadCount(final long unreadCount) {
            this.unreadCount = unreadCount;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof MessageDto.ConversationResponse)) return false;
            final MessageDto.ConversationResponse other = (MessageDto.ConversationResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getUnreadCount() != other.getUnreadCount()) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$participants = this.getParticipants();
            final java.lang.Object other$participants = other.getParticipants();
            if (this$participants == null ? other$participants != null : !this$participants.equals(other$participants)) return false;
            final java.lang.Object this$lastMessage = this.getLastMessage();
            final java.lang.Object other$lastMessage = other.getLastMessage();
            if (this$lastMessage == null ? other$lastMessage != null : !this$lastMessage.equals(other$lastMessage)) return false;
            final java.lang.Object this$lastMessageAt = this.getLastMessageAt();
            final java.lang.Object other$lastMessageAt = other.getLastMessageAt();
            if (this$lastMessageAt == null ? other$lastMessageAt != null : !this$lastMessageAt.equals(other$lastMessageAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof MessageDto.ConversationResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final long $unreadCount = this.getUnreadCount();
            result = result * PRIME + (int) ($unreadCount >>> 32 ^ $unreadCount);
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $participants = this.getParticipants();
            result = result * PRIME + ($participants == null ? 43 : $participants.hashCode());
            final java.lang.Object $lastMessage = this.getLastMessage();
            result = result * PRIME + ($lastMessage == null ? 43 : $lastMessage.hashCode());
            final java.lang.Object $lastMessageAt = this.getLastMessageAt();
            result = result * PRIME + ($lastMessageAt == null ? 43 : $lastMessageAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "MessageDto.ConversationResponse(id=" + this.getId() + ", participants=" + this.getParticipants() + ", lastMessage=" + this.getLastMessage() + ", lastMessageAt=" + this.getLastMessageAt() + ", unreadCount=" + this.getUnreadCount() + ")";
        }
    }
}
