// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.dto;

import com.example.demo.entity.Notification;
import com.example.demo.enums.NotificationType;
import java.time.LocalDateTime;

public class NotificationDto {

    public static class NotificationResponse {
        private Long id;
        private NotificationType type;
        private String title;
        private String body;
        private Long referenceId;
        private boolean read;
        private LocalDateTime createdAt;

        public static NotificationResponse from(Notification notification) {
            NotificationResponse dto = new NotificationResponse();
            dto.setId(notification.getId());
            dto.setType(notification.getType());
            dto.setTitle(notification.getTitle());
            dto.setBody(notification.getBody());
            dto.setReferenceId(notification.getReferenceId());
            dto.setRead(notification.isRead());
            dto.setCreatedAt(notification.getCreatedAt());
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public NotificationResponse() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public NotificationType getType() {
            return this.type;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getTitle() {
            return this.title;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getBody() {
            return this.body;
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getReferenceId() {
            return this.referenceId;
        }

        @java.lang.SuppressWarnings("all")
        
        public boolean isRead() {
            return this.read;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setType(final NotificationType type) {
            this.type = type;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setTitle(final String title) {
            this.title = title;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setBody(final String body) {
            this.body = body;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setReferenceId(final Long referenceId) {
            this.referenceId = referenceId;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setRead(final boolean read) {
            this.read = read;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCreatedAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof NotificationDto.NotificationResponse)) return false;
            final NotificationDto.NotificationResponse other = (NotificationDto.NotificationResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.isRead() != other.isRead()) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$referenceId = this.getReferenceId();
            final java.lang.Object other$referenceId = other.getReferenceId();
            if (this$referenceId == null ? other$referenceId != null : !this$referenceId.equals(other$referenceId)) return false;
            final java.lang.Object this$type = this.getType();
            final java.lang.Object other$type = other.getType();
            if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
            final java.lang.Object this$title = this.getTitle();
            final java.lang.Object other$title = other.getTitle();
            if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
            final java.lang.Object this$body = this.getBody();
            final java.lang.Object other$body = other.getBody();
            if (this$body == null ? other$body != null : !this$body.equals(other$body)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof NotificationDto.NotificationResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + (this.isRead() ? 79 : 97);
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $referenceId = this.getReferenceId();
            result = result * PRIME + ($referenceId == null ? 43 : $referenceId.hashCode());
            final java.lang.Object $type = this.getType();
            result = result * PRIME + ($type == null ? 43 : $type.hashCode());
            final java.lang.Object $title = this.getTitle();
            result = result * PRIME + ($title == null ? 43 : $title.hashCode());
            final java.lang.Object $body = this.getBody();
            result = result * PRIME + ($body == null ? 43 : $body.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "NotificationDto.NotificationResponse(id=" + this.getId() + ", type=" + this.getType() + ", title=" + this.getTitle() + ", body=" + this.getBody() + ", referenceId=" + this.getReferenceId() + ", read=" + this.isRead() + ", createdAt=" + this.getCreatedAt() + ")";
        }
    }


    public static class UnreadCountResponse {
        private long count;

        public UnreadCountResponse(long count) {
            this.count = count;
        }

        @java.lang.SuppressWarnings("all")
        
        public long getCount() {
            return this.count;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCount(final long count) {
            this.count = count;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof NotificationDto.UnreadCountResponse)) return false;
            final NotificationDto.UnreadCountResponse other = (NotificationDto.UnreadCountResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getCount() != other.getCount()) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof NotificationDto.UnreadCountResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final long $count = this.getCount();
            result = result * PRIME + (int) ($count >>> 32 ^ $count);
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "NotificationDto.UnreadCountResponse(count=" + this.getCount() + ")";
        }
    }
}
