// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.dto;

import com.example.demo.entity.Comment;
import com.example.demo.entity.Post;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public class PostDto {

    public static class CreatePostRequest {
        @NotBlank
        private String content;
        private String imageUrl;
        @NotNull
        private Double latitude;
        @NotNull
        private Double longitude;

        @java.lang.SuppressWarnings("all")
        
        public CreatePostRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public String getContent() {
            return this.content;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getImageUrl() {
            return this.imageUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setContent(final String content) {
            this.content = content;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setImageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof PostDto.CreatePostRequest)) return false;
            final PostDto.CreatePostRequest other = (PostDto.CreatePostRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            final java.lang.Object this$content = this.getContent();
            final java.lang.Object other$content = other.getContent();
            if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
            final java.lang.Object this$imageUrl = this.getImageUrl();
            final java.lang.Object other$imageUrl = other.getImageUrl();
            if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof PostDto.CreatePostRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            final java.lang.Object $content = this.getContent();
            result = result * PRIME + ($content == null ? 43 : $content.hashCode());
            final java.lang.Object $imageUrl = this.getImageUrl();
            result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "PostDto.CreatePostRequest(content=" + this.getContent() + ", imageUrl=" + this.getImageUrl() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ")";
        }
    }


    public static class PostResponse {
        private Long id;
        private UserDto.UserProfileDto author;
        private String content;
        private String imageUrl;
        private Double latitude;
        private Double longitude;
        private int likeCount;
        private int commentCount;
        private boolean likedByMe;
        private LocalDateTime createdAt;

        public static PostResponse from(Post post, boolean likedByMe) {
            PostResponse dto = new PostResponse();
            dto.setId(post.getId());
            dto.setAuthor(UserDto.UserProfileDto.from(post.getAuthor()));
            dto.setContent(post.getContent());
            dto.setImageUrl(post.getImageUrl());
            dto.setLatitude(post.getLatitude());
            dto.setLongitude(post.getLongitude());
            dto.setLikeCount(post.getLikeCount());
            dto.setCommentCount(post.getCommentCount());
            dto.setLikedByMe(likedByMe);
            dto.setCreatedAt(post.getCreatedAt());
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public PostResponse() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public UserDto.UserProfileDto getAuthor() {
            return this.author;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getContent() {
            return this.content;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getImageUrl() {
            return this.imageUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public int getLikeCount() {
            return this.likeCount;
        }

        @java.lang.SuppressWarnings("all")
        
        public int getCommentCount() {
            return this.commentCount;
        }

        @java.lang.SuppressWarnings("all")
        
        public boolean isLikedByMe() {
            return this.likedByMe;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setAuthor(final UserDto.UserProfileDto author) {
            this.author = author;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setContent(final String content) {
            this.content = content;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setImageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLikeCount(final int likeCount) {
            this.likeCount = likeCount;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCommentCount(final int commentCount) {
            this.commentCount = commentCount;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLikedByMe(final boolean likedByMe) {
            this.likedByMe = likedByMe;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCreatedAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof PostDto.PostResponse)) return false;
            final PostDto.PostResponse other = (PostDto.PostResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getLikeCount() != other.getLikeCount()) return false;
            if (this.getCommentCount() != other.getCommentCount()) return false;
            if (this.isLikedByMe() != other.isLikedByMe()) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            final java.lang.Object this$author = this.getAuthor();
            final java.lang.Object other$author = other.getAuthor();
            if (this$author == null ? other$author != null : !this$author.equals(other$author)) return false;
            final java.lang.Object this$content = this.getContent();
            final java.lang.Object other$content = other.getContent();
            if (this$content == null ? other$content != null : !this$content.equals(other$content)) return false;
            final java.lang.Object this$imageUrl = this.getImageUrl();
            final java.lang.Object other$imageUrl = other.getImageUrl();
            if (this$imageUrl == null ? other$imageUrl != null : !this$imageUrl.equals(other$imageUrl)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof PostDto.PostResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getLikeCount();
            result = result * PRIME + this.getCommentCount();
            result = result * PRIME + (this.isLikedByMe() ? 79 : 97);
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            final java.lang.Object $author = this.getAuthor();
            result = result * PRIME + ($author == null ? 43 : $author.hashCode());
            final java.lang.Object $content = this.getContent();
            result = result * PRIME + ($content == null ? 43 : $content.hashCode());
            final java.lang.Object $imageUrl = this.getImageUrl();
            result = result * PRIME + ($imageUrl == null ? 43 : $imageUrl.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "PostDto.PostResponse(id=" + this.getId() + ", author=" + this.getAuthor() + ", content=" + this.getContent() + ", imageUrl=" + this.getImageUrl() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", likeCount=" + this.getLikeCount() + ", commentCount=" + this.getCommentCount() + ", likedByMe=" + this.isLikedByMe() + ", createdAt=" + this.getCreatedAt() + ")";
        }
    }


    public static class CommentRequest {
        @NotBlank
        private String text;

        @java.lang.SuppressWarnings("all")
        
        public CommentRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public String getText() {
            return this.text;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setText(final String text) {
            this.text = text;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof PostDto.CommentRequest)) return false;
            final PostDto.CommentRequest other = (PostDto.CommentRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$text = this.getText();
            final java.lang.Object other$text = other.getText();
            if (this$text == null ? other$text != null : !this$text.equals(other$text)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof PostDto.CommentRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $text = this.getText();
            result = result * PRIME + ($text == null ? 43 : $text.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "PostDto.CommentRequest(text=" + this.getText() + ")";
        }
    }


    public static class CommentResponse {
        private Long id;
        private UserDto.UserProfileDto author;
        private String text;
        private LocalDateTime createdAt;

        public static CommentResponse from(Comment comment) {
            CommentResponse dto = new CommentResponse();
            dto.setId(comment.getId());
            dto.setAuthor(UserDto.UserProfileDto.from(comment.getAuthor()));
            dto.setText(comment.getText());
            dto.setCreatedAt(comment.getCreatedAt());
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public CommentResponse() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public UserDto.UserProfileDto getAuthor() {
            return this.author;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getText() {
            return this.text;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setAuthor(final UserDto.UserProfileDto author) {
            this.author = author;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setText(final String text) {
            this.text = text;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCreatedAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof PostDto.CommentResponse)) return false;
            final PostDto.CommentResponse other = (PostDto.CommentResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$author = this.getAuthor();
            final java.lang.Object other$author = other.getAuthor();
            if (this$author == null ? other$author != null : !this$author.equals(other$author)) return false;
            final java.lang.Object this$text = this.getText();
            final java.lang.Object other$text = other.getText();
            if (this$text == null ? other$text != null : !this$text.equals(other$text)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof PostDto.CommentResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $author = this.getAuthor();
            result = result * PRIME + ($author == null ? 43 : $author.hashCode());
            final java.lang.Object $text = this.getText();
            result = result * PRIME + ($text == null ? 43 : $text.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "PostDto.CommentResponse(id=" + this.getId() + ", author=" + this.getAuthor() + ", text=" + this.getText() + ", createdAt=" + this.getCreatedAt() + ")";
        }
    }
}
