// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.dto;

import com.example.demo.entity.Booking;
import com.example.demo.entity.ServiceListing;
import com.example.demo.enums.BookingStatus;
import com.example.demo.enums.ServiceCategory;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public class ServiceDto {

    public static class CreateServiceRequest {
        @NotNull
        private ServiceCategory category;
        @NotBlank
        private String title;
        private String description;
        @NotNull
        private BigDecimal price;
        private String priceUnit;
        @NotNull
        private Double latitude;
        @NotNull
        private Double longitude;

        @java.lang.SuppressWarnings("all")
        
        public CreateServiceRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public ServiceCategory getCategory() {
            return this.category;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getTitle() {
            return this.title;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getDescription() {
            return this.description;
        }

        @java.lang.SuppressWarnings("all")
        
        public BigDecimal getPrice() {
            return this.price;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getPriceUnit() {
            return this.priceUnit;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCategory(final ServiceCategory category) {
            this.category = category;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setTitle(final String title) {
            this.title = title;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setDescription(final String description) {
            this.description = description;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setPrice(final BigDecimal price) {
            this.price = price;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setPriceUnit(final String priceUnit) {
            this.priceUnit = priceUnit;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ServiceDto.CreateServiceRequest)) return false;
            final ServiceDto.CreateServiceRequest other = (ServiceDto.CreateServiceRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$title = this.getTitle();
            final java.lang.Object other$title = other.getTitle();
            if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
            final java.lang.Object this$description = this.getDescription();
            final java.lang.Object other$description = other.getDescription();
            if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
            final java.lang.Object this$price = this.getPrice();
            final java.lang.Object other$price = other.getPrice();
            if (this$price == null ? other$price != null : !this$price.equals(other$price)) return false;
            final java.lang.Object this$priceUnit = this.getPriceUnit();
            final java.lang.Object other$priceUnit = other.getPriceUnit();
            if (this$priceUnit == null ? other$priceUnit != null : !this$priceUnit.equals(other$priceUnit)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ServiceDto.CreateServiceRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $title = this.getTitle();
            result = result * PRIME + ($title == null ? 43 : $title.hashCode());
            final java.lang.Object $description = this.getDescription();
            result = result * PRIME + ($description == null ? 43 : $description.hashCode());
            final java.lang.Object $price = this.getPrice();
            result = result * PRIME + ($price == null ? 43 : $price.hashCode());
            final java.lang.Object $priceUnit = this.getPriceUnit();
            result = result * PRIME + ($priceUnit == null ? 43 : $priceUnit.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "ServiceDto.CreateServiceRequest(category=" + this.getCategory() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", price=" + this.getPrice() + ", priceUnit=" + this.getPriceUnit() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ")";
        }
    }


    public static class ServiceListingResponse {
        private Long id;
        private UserDto.UserProfileDto provider;
        private ServiceCategory category;
        private String title;
        private String description;
        private BigDecimal price;
        private String priceUnit;
        private double rating;
        private int ratingCount;
        private Double latitude;
        private Double longitude;
        private LocalDateTime createdAt;

        public static ServiceListingResponse from(ServiceListing s) {
            ServiceListingResponse dto = new ServiceListingResponse();
            dto.setId(s.getId());
            dto.setProvider(UserDto.UserProfileDto.from(s.getProvider()));
            dto.setCategory(s.getCategory());
            dto.setTitle(s.getTitle());
            dto.setDescription(s.getDescription());
            dto.setPrice(s.getPrice());
            dto.setPriceUnit(s.getPriceUnit());
            dto.setRating(s.getRating());
            dto.setRatingCount(s.getRatingCount());
            dto.setLatitude(s.getLatitude());
            dto.setLongitude(s.getLongitude());
            dto.setCreatedAt(s.getCreatedAt());
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public ServiceListingResponse() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public UserDto.UserProfileDto getProvider() {
            return this.provider;
        }

        @java.lang.SuppressWarnings("all")
        
        public ServiceCategory getCategory() {
            return this.category;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getTitle() {
            return this.title;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getDescription() {
            return this.description;
        }

        @java.lang.SuppressWarnings("all")
        
        public BigDecimal getPrice() {
            return this.price;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getPriceUnit() {
            return this.priceUnit;
        }

        @java.lang.SuppressWarnings("all")
        
        public double getRating() {
            return this.rating;
        }

        @java.lang.SuppressWarnings("all")
        
        public int getRatingCount() {
            return this.ratingCount;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setProvider(final UserDto.UserProfileDto provider) {
            this.provider = provider;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCategory(final ServiceCategory category) {
            this.category = category;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setTitle(final String title) {
            this.title = title;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setDescription(final String description) {
            this.description = description;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setPrice(final BigDecimal price) {
            this.price = price;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setPriceUnit(final String priceUnit) {
            this.priceUnit = priceUnit;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setRating(final double rating) {
            this.rating = rating;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setRatingCount(final int ratingCount) {
            this.ratingCount = ratingCount;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCreatedAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ServiceDto.ServiceListingResponse)) return false;
            final ServiceDto.ServiceListingResponse other = (ServiceDto.ServiceListingResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (java.lang.Double.compare(this.getRating(), other.getRating()) != 0) return false;
            if (this.getRatingCount() != other.getRatingCount()) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            final java.lang.Object this$provider = this.getProvider();
            final java.lang.Object other$provider = other.getProvider();
            if (this$provider == null ? other$provider != null : !this$provider.equals(other$provider)) return false;
            final java.lang.Object this$category = this.getCategory();
            final java.lang.Object other$category = other.getCategory();
            if (this$category == null ? other$category != null : !this$category.equals(other$category)) return false;
            final java.lang.Object this$title = this.getTitle();
            final java.lang.Object other$title = other.getTitle();
            if (this$title == null ? other$title != null : !this$title.equals(other$title)) return false;
            final java.lang.Object this$description = this.getDescription();
            final java.lang.Object other$description = other.getDescription();
            if (this$description == null ? other$description != null : !this$description.equals(other$description)) return false;
            final java.lang.Object this$price = this.getPrice();
            final java.lang.Object other$price = other.getPrice();
            if (this$price == null ? other$price != null : !this$price.equals(other$price)) return false;
            final java.lang.Object this$priceUnit = this.getPriceUnit();
            final java.lang.Object other$priceUnit = other.getPriceUnit();
            if (this$priceUnit == null ? other$priceUnit != null : !this$priceUnit.equals(other$priceUnit)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ServiceDto.ServiceListingResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final long $rating = java.lang.Double.doubleToLongBits(this.getRating());
            result = result * PRIME + (int) ($rating >>> 32 ^ $rating);
            result = result * PRIME + this.getRatingCount();
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            final java.lang.Object $provider = this.getProvider();
            result = result * PRIME + ($provider == null ? 43 : $provider.hashCode());
            final java.lang.Object $category = this.getCategory();
            result = result * PRIME + ($category == null ? 43 : $category.hashCode());
            final java.lang.Object $title = this.getTitle();
            result = result * PRIME + ($title == null ? 43 : $title.hashCode());
            final java.lang.Object $description = this.getDescription();
            result = result * PRIME + ($description == null ? 43 : $description.hashCode());
            final java.lang.Object $price = this.getPrice();
            result = result * PRIME + ($price == null ? 43 : $price.hashCode());
            final java.lang.Object $priceUnit = this.getPriceUnit();
            result = result * PRIME + ($priceUnit == null ? 43 : $priceUnit.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "ServiceDto.ServiceListingResponse(id=" + this.getId() + ", provider=" + this.getProvider() + ", category=" + this.getCategory() + ", title=" + this.getTitle() + ", description=" + this.getDescription() + ", price=" + this.getPrice() + ", priceUnit=" + this.getPriceUnit() + ", rating=" + this.getRating() + ", ratingCount=" + this.getRatingCount() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", createdAt=" + this.getCreatedAt() + ")";
        }
    }


    public static class CreateBookingRequest {
        @NotNull
        private Long serviceId;
        private String notes;
        private LocalDateTime scheduledAt;

        @java.lang.SuppressWarnings("all")
        
        public CreateBookingRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getServiceId() {
            return this.serviceId;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getNotes() {
            return this.notes;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getScheduledAt() {
            return this.scheduledAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setServiceId(final Long serviceId) {
            this.serviceId = serviceId;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setNotes(final String notes) {
            this.notes = notes;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setScheduledAt(final LocalDateTime scheduledAt) {
            this.scheduledAt = scheduledAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ServiceDto.CreateBookingRequest)) return false;
            final ServiceDto.CreateBookingRequest other = (ServiceDto.CreateBookingRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$serviceId = this.getServiceId();
            final java.lang.Object other$serviceId = other.getServiceId();
            if (this$serviceId == null ? other$serviceId != null : !this$serviceId.equals(other$serviceId)) return false;
            final java.lang.Object this$notes = this.getNotes();
            final java.lang.Object other$notes = other.getNotes();
            if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
            final java.lang.Object this$scheduledAt = this.getScheduledAt();
            final java.lang.Object other$scheduledAt = other.getScheduledAt();
            if (this$scheduledAt == null ? other$scheduledAt != null : !this$scheduledAt.equals(other$scheduledAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ServiceDto.CreateBookingRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $serviceId = this.getServiceId();
            result = result * PRIME + ($serviceId == null ? 43 : $serviceId.hashCode());
            final java.lang.Object $notes = this.getNotes();
            result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
            final java.lang.Object $scheduledAt = this.getScheduledAt();
            result = result * PRIME + ($scheduledAt == null ? 43 : $scheduledAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "ServiceDto.CreateBookingRequest(serviceId=" + this.getServiceId() + ", notes=" + this.getNotes() + ", scheduledAt=" + this.getScheduledAt() + ")";
        }
    }


    public static class BookingResponse {
        private Long id;
        private ServiceListingResponse service;
        private UserDto.UserProfileDto customer;
        private BookingStatus status;
        private String notes;
        private LocalDateTime scheduledAt;
        private LocalDateTime createdAt;

        public static BookingResponse from(Booking b) {
            BookingResponse dto = new BookingResponse();
            dto.setId(b.getId());
            dto.setService(ServiceListingResponse.from(b.getService()));
            dto.setCustomer(UserDto.UserProfileDto.from(b.getCustomer()));
            dto.setStatus(b.getStatus());
            dto.setNotes(b.getNotes());
            dto.setScheduledAt(b.getScheduledAt());
            dto.setCreatedAt(b.getCreatedAt());
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public BookingResponse() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public ServiceListingResponse getService() {
            return this.service;
        }

        @java.lang.SuppressWarnings("all")
        
        public UserDto.UserProfileDto getCustomer() {
            return this.customer;
        }

        @java.lang.SuppressWarnings("all")
        
        public BookingStatus getStatus() {
            return this.status;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getNotes() {
            return this.notes;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getScheduledAt() {
            return this.scheduledAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setService(final ServiceListingResponse service) {
            this.service = service;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCustomer(final UserDto.UserProfileDto customer) {
            this.customer = customer;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setStatus(final BookingStatus status) {
            this.status = status;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setNotes(final String notes) {
            this.notes = notes;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setScheduledAt(final LocalDateTime scheduledAt) {
            this.scheduledAt = scheduledAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCreatedAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ServiceDto.BookingResponse)) return false;
            final ServiceDto.BookingResponse other = (ServiceDto.BookingResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$service = this.getService();
            final java.lang.Object other$service = other.getService();
            if (this$service == null ? other$service != null : !this$service.equals(other$service)) return false;
            final java.lang.Object this$customer = this.getCustomer();
            final java.lang.Object other$customer = other.getCustomer();
            if (this$customer == null ? other$customer != null : !this$customer.equals(other$customer)) return false;
            final java.lang.Object this$status = this.getStatus();
            final java.lang.Object other$status = other.getStatus();
            if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
            final java.lang.Object this$notes = this.getNotes();
            final java.lang.Object other$notes = other.getNotes();
            if (this$notes == null ? other$notes != null : !this$notes.equals(other$notes)) return false;
            final java.lang.Object this$scheduledAt = this.getScheduledAt();
            final java.lang.Object other$scheduledAt = other.getScheduledAt();
            if (this$scheduledAt == null ? other$scheduledAt != null : !this$scheduledAt.equals(other$scheduledAt)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ServiceDto.BookingResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $service = this.getService();
            result = result * PRIME + ($service == null ? 43 : $service.hashCode());
            final java.lang.Object $customer = this.getCustomer();
            result = result * PRIME + ($customer == null ? 43 : $customer.hashCode());
            final java.lang.Object $status = this.getStatus();
            result = result * PRIME + ($status == null ? 43 : $status.hashCode());
            final java.lang.Object $notes = this.getNotes();
            result = result * PRIME + ($notes == null ? 43 : $notes.hashCode());
            final java.lang.Object $scheduledAt = this.getScheduledAt();
            result = result * PRIME + ($scheduledAt == null ? 43 : $scheduledAt.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "ServiceDto.BookingResponse(id=" + this.getId() + ", service=" + this.getService() + ", customer=" + this.getCustomer() + ", status=" + this.getStatus() + ", notes=" + this.getNotes() + ", scheduledAt=" + this.getScheduledAt() + ", createdAt=" + this.getCreatedAt() + ")";
        }
    }


    public static class UpdateBookingStatusRequest {
        @NotNull
        private BookingStatus status;

        @java.lang.SuppressWarnings("all")
        
        public UpdateBookingStatusRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public BookingStatus getStatus() {
            return this.status;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setStatus(final BookingStatus status) {
            this.status = status;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof ServiceDto.UpdateBookingStatusRequest)) return false;
            final ServiceDto.UpdateBookingStatusRequest other = (ServiceDto.UpdateBookingStatusRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$status = this.getStatus();
            final java.lang.Object other$status = other.getStatus();
            if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof ServiceDto.UpdateBookingStatusRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $status = this.getStatus();
            result = result * PRIME + ($status == null ? 43 : $status.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "ServiceDto.UpdateBookingStatusRequest(status=" + this.getStatus() + ")";
        }
    }
}
