// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.dto;

import com.example.demo.entity.SosAlert;
import com.example.demo.enums.AlertStatus;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public class SosDto {

    public static class SosAlertRequest {
        @NotNull
        private Double latitude;
        @NotNull
        private Double longitude;
        private String message;

        @java.lang.SuppressWarnings("all")
        
        public SosAlertRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getMessage() {
            return this.message;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setMessage(final String message) {
            this.message = message;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof SosDto.SosAlertRequest)) return false;
            final SosDto.SosAlertRequest other = (SosDto.SosAlertRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            final java.lang.Object this$message = this.getMessage();
            final java.lang.Object other$message = other.getMessage();
            if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof SosDto.SosAlertRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            final java.lang.Object $message = this.getMessage();
            result = result * PRIME + ($message == null ? 43 : $message.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "SosDto.SosAlertRequest(latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", message=" + this.getMessage() + ")";
        }
    }


    public static class SosAlertResponse {
        private Long id;
        private UserDto.UserProfileDto user;
        private Double latitude;
        private Double longitude;
        private String message;
        private AlertStatus status;
        private int nearbyUsersNotified;
        private LocalDateTime createdAt;

        public static SosAlertResponse from(SosAlert alert) {
            SosAlertResponse dto = new SosAlertResponse();
            dto.setId(alert.getId());
            dto.setUser(UserDto.UserProfileDto.from(alert.getUser()));
            dto.setLatitude(alert.getLatitude());
            dto.setLongitude(alert.getLongitude());
            dto.setMessage(alert.getMessage());
            dto.setStatus(alert.getStatus());
            dto.setNearbyUsersNotified(alert.getNearbyUsersNotified());
            dto.setCreatedAt(alert.getCreatedAt());
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public SosAlertResponse() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public UserDto.UserProfileDto getUser() {
            return this.user;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getMessage() {
            return this.message;
        }

        @java.lang.SuppressWarnings("all")
        
        public AlertStatus getStatus() {
            return this.status;
        }

        @java.lang.SuppressWarnings("all")
        
        public int getNearbyUsersNotified() {
            return this.nearbyUsersNotified;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setUser(final UserDto.UserProfileDto user) {
            this.user = user;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setMessage(final String message) {
            this.message = message;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setStatus(final AlertStatus status) {
            this.status = status;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setNearbyUsersNotified(final int nearbyUsersNotified) {
            this.nearbyUsersNotified = nearbyUsersNotified;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCreatedAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof SosDto.SosAlertResponse)) return false;
            final SosDto.SosAlertResponse other = (SosDto.SosAlertResponse) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.getNearbyUsersNotified() != other.getNearbyUsersNotified()) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            final java.lang.Object this$user = this.getUser();
            final java.lang.Object other$user = other.getUser();
            if (this$user == null ? other$user != null : !this$user.equals(other$user)) return false;
            final java.lang.Object this$message = this.getMessage();
            final java.lang.Object other$message = other.getMessage();
            if (this$message == null ? other$message != null : !this$message.equals(other$message)) return false;
            final java.lang.Object this$status = this.getStatus();
            final java.lang.Object other$status = other.getStatus();
            if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof SosDto.SosAlertResponse;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + this.getNearbyUsersNotified();
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            final java.lang.Object $user = this.getUser();
            result = result * PRIME + ($user == null ? 43 : $user.hashCode());
            final java.lang.Object $message = this.getMessage();
            result = result * PRIME + ($message == null ? 43 : $message.hashCode());
            final java.lang.Object $status = this.getStatus();
            result = result * PRIME + ($status == null ? 43 : $status.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "SosDto.SosAlertResponse(id=" + this.getId() + ", user=" + this.getUser() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", message=" + this.getMessage() + ", status=" + this.getStatus() + ", nearbyUsersNotified=" + this.getNearbyUsersNotified() + ", createdAt=" + this.getCreatedAt() + ")";
        }
    }
}
