// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.dto;

import com.example.demo.entity.User;
import com.example.demo.enums.Role;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;

public class UserDto {

    public static class UserProfileDto {
        private Long id;
        private String name;
        private String email;
        private String phone;
        private String avatarUrl;
        private String bio;
        private Double latitude;
        private Double longitude;
        private Role role;
        private boolean verified;
        private LocalDateTime createdAt;

        public static UserProfileDto from(User user) {
            UserProfileDto dto = new UserProfileDto();
            dto.setId(user.getId());
            dto.setName(user.getName());
            dto.setEmail(user.getEmail());
            dto.setPhone(user.getPhone());
            dto.setAvatarUrl(user.getAvatarUrl());
            dto.setBio(user.getBio());
            dto.setLatitude(user.getLatitude());
            dto.setLongitude(user.getLongitude());
            dto.setRole(user.getRole());
            dto.setVerified(user.isVerified());
            dto.setCreatedAt(user.getCreatedAt());
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public UserProfileDto() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getEmail() {
            return this.email;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getPhone() {
            return this.phone;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getAvatarUrl() {
            return this.avatarUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getBio() {
            return this.bio;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Role getRole() {
            return this.role;
        }

        @java.lang.SuppressWarnings("all")
        
        public boolean isVerified() {
            return this.verified;
        }

        @java.lang.SuppressWarnings("all")
        
        public LocalDateTime getCreatedAt() {
            return this.createdAt;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setEmail(final String email) {
            this.email = email;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setPhone(final String phone) {
            this.phone = phone;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setAvatarUrl(final String avatarUrl) {
            this.avatarUrl = avatarUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setBio(final String bio) {
            this.bio = bio;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setRole(final Role role) {
            this.role = role;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setVerified(final boolean verified) {
            this.verified = verified;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setCreatedAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof UserDto.UserProfileDto)) return false;
            final UserDto.UserProfileDto other = (UserDto.UserProfileDto) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (this.isVerified() != other.isVerified()) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$email = this.getEmail();
            final java.lang.Object other$email = other.getEmail();
            if (this$email == null ? other$email != null : !this$email.equals(other$email)) return false;
            final java.lang.Object this$phone = this.getPhone();
            final java.lang.Object other$phone = other.getPhone();
            if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
            final java.lang.Object this$avatarUrl = this.getAvatarUrl();
            final java.lang.Object other$avatarUrl = other.getAvatarUrl();
            if (this$avatarUrl == null ? other$avatarUrl != null : !this$avatarUrl.equals(other$avatarUrl)) return false;
            final java.lang.Object this$bio = this.getBio();
            final java.lang.Object other$bio = other.getBio();
            if (this$bio == null ? other$bio != null : !this$bio.equals(other$bio)) return false;
            final java.lang.Object this$role = this.getRole();
            final java.lang.Object other$role = other.getRole();
            if (this$role == null ? other$role != null : !this$role.equals(other$role)) return false;
            final java.lang.Object this$createdAt = this.getCreatedAt();
            final java.lang.Object other$createdAt = other.getCreatedAt();
            if (this$createdAt == null ? other$createdAt != null : !this$createdAt.equals(other$createdAt)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof UserDto.UserProfileDto;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            result = result * PRIME + (this.isVerified() ? 79 : 97);
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $email = this.getEmail();
            result = result * PRIME + ($email == null ? 43 : $email.hashCode());
            final java.lang.Object $phone = this.getPhone();
            result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
            final java.lang.Object $avatarUrl = this.getAvatarUrl();
            result = result * PRIME + ($avatarUrl == null ? 43 : $avatarUrl.hashCode());
            final java.lang.Object $bio = this.getBio();
            result = result * PRIME + ($bio == null ? 43 : $bio.hashCode());
            final java.lang.Object $role = this.getRole();
            result = result * PRIME + ($role == null ? 43 : $role.hashCode());
            final java.lang.Object $createdAt = this.getCreatedAt();
            result = result * PRIME + ($createdAt == null ? 43 : $createdAt.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "UserDto.UserProfileDto(id=" + this.getId() + ", name=" + this.getName() + ", email=" + this.getEmail() + ", phone=" + this.getPhone() + ", avatarUrl=" + this.getAvatarUrl() + ", bio=" + this.getBio() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", role=" + this.getRole() + ", verified=" + this.isVerified() + ", createdAt=" + this.getCreatedAt() + ")";
        }
    }


    public static class UpdateProfileRequest {
        @NotBlank
        private String name;
        private String phone;
        private String bio;
        private String avatarUrl;

        @java.lang.SuppressWarnings("all")
        
        public UpdateProfileRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getPhone() {
            return this.phone;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getBio() {
            return this.bio;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getAvatarUrl() {
            return this.avatarUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setPhone(final String phone) {
            this.phone = phone;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setBio(final String bio) {
            this.bio = bio;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setAvatarUrl(final String avatarUrl) {
            this.avatarUrl = avatarUrl;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof UserDto.UpdateProfileRequest)) return false;
            final UserDto.UpdateProfileRequest other = (UserDto.UpdateProfileRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$phone = this.getPhone();
            final java.lang.Object other$phone = other.getPhone();
            if (this$phone == null ? other$phone != null : !this$phone.equals(other$phone)) return false;
            final java.lang.Object this$bio = this.getBio();
            final java.lang.Object other$bio = other.getBio();
            if (this$bio == null ? other$bio != null : !this$bio.equals(other$bio)) return false;
            final java.lang.Object this$avatarUrl = this.getAvatarUrl();
            final java.lang.Object other$avatarUrl = other.getAvatarUrl();
            if (this$avatarUrl == null ? other$avatarUrl != null : !this$avatarUrl.equals(other$avatarUrl)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof UserDto.UpdateProfileRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $phone = this.getPhone();
            result = result * PRIME + ($phone == null ? 43 : $phone.hashCode());
            final java.lang.Object $bio = this.getBio();
            result = result * PRIME + ($bio == null ? 43 : $bio.hashCode());
            final java.lang.Object $avatarUrl = this.getAvatarUrl();
            result = result * PRIME + ($avatarUrl == null ? 43 : $avatarUrl.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "UserDto.UpdateProfileRequest(name=" + this.getName() + ", phone=" + this.getPhone() + ", bio=" + this.getBio() + ", avatarUrl=" + this.getAvatarUrl() + ")";
        }
    }


    public static class LocationUpdateRequest {
        @NotNull
        private Double latitude;
        @NotNull
        private Double longitude;

        @java.lang.SuppressWarnings("all")
        
        public LocationUpdateRequest() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof UserDto.LocationUpdateRequest)) return false;
            final UserDto.LocationUpdateRequest other = (UserDto.LocationUpdateRequest) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof UserDto.LocationUpdateRequest;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "UserDto.LocationUpdateRequest(latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ")";
        }
    }


    public static class NearbyUserDto {
        private Long id;
        private String name;
        private String avatarUrl;
        private Double latitude;
        private Double longitude;
        private double distanceKm;

        public static NearbyUserDto from(User user, double distanceKm) {
            NearbyUserDto dto = new NearbyUserDto();
            dto.setId(user.getId());
            dto.setName(user.getName());
            dto.setAvatarUrl(user.getAvatarUrl());
            dto.setLatitude(user.getLatitude());
            dto.setLongitude(user.getLongitude());
            dto.setDistanceKm(distanceKm);
            return dto;
        }

        @java.lang.SuppressWarnings("all")
        
        public NearbyUserDto() {
        }

        @java.lang.SuppressWarnings("all")
        
        public Long getId() {
            return this.id;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getName() {
            return this.name;
        }

        @java.lang.SuppressWarnings("all")
        
        public String getAvatarUrl() {
            return this.avatarUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLatitude() {
            return this.latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public Double getLongitude() {
            return this.longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public double getDistanceKm() {
            return this.distanceKm;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setId(final Long id) {
            this.id = id;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setName(final String name) {
            this.name = name;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setAvatarUrl(final String avatarUrl) {
            this.avatarUrl = avatarUrl;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLatitude(final Double latitude) {
            this.latitude = latitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setLongitude(final Double longitude) {
            this.longitude = longitude;
        }

        @java.lang.SuppressWarnings("all")
        
        public void setDistanceKm(final double distanceKm) {
            this.distanceKm = distanceKm;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public boolean equals(final java.lang.Object o) {
            if (o == this) return true;
            if (!(o instanceof UserDto.NearbyUserDto)) return false;
            final UserDto.NearbyUserDto other = (UserDto.NearbyUserDto) o;
            if (!other.canEqual((java.lang.Object) this)) return false;
            if (java.lang.Double.compare(this.getDistanceKm(), other.getDistanceKm()) != 0) return false;
            final java.lang.Object this$id = this.getId();
            final java.lang.Object other$id = other.getId();
            if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
            final java.lang.Object this$latitude = this.getLatitude();
            final java.lang.Object other$latitude = other.getLatitude();
            if (this$latitude == null ? other$latitude != null : !this$latitude.equals(other$latitude)) return false;
            final java.lang.Object this$longitude = this.getLongitude();
            final java.lang.Object other$longitude = other.getLongitude();
            if (this$longitude == null ? other$longitude != null : !this$longitude.equals(other$longitude)) return false;
            final java.lang.Object this$name = this.getName();
            final java.lang.Object other$name = other.getName();
            if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
            final java.lang.Object this$avatarUrl = this.getAvatarUrl();
            final java.lang.Object other$avatarUrl = other.getAvatarUrl();
            if (this$avatarUrl == null ? other$avatarUrl != null : !this$avatarUrl.equals(other$avatarUrl)) return false;
            return true;
        }

        @java.lang.SuppressWarnings("all")
        
        protected boolean canEqual(final java.lang.Object other) {
            return other instanceof UserDto.NearbyUserDto;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public int hashCode() {
            final int PRIME = 59;
            int result = 1;
            final long $distanceKm = java.lang.Double.doubleToLongBits(this.getDistanceKm());
            result = result * PRIME + (int) ($distanceKm >>> 32 ^ $distanceKm);
            final java.lang.Object $id = this.getId();
            result = result * PRIME + ($id == null ? 43 : $id.hashCode());
            final java.lang.Object $latitude = this.getLatitude();
            result = result * PRIME + ($latitude == null ? 43 : $latitude.hashCode());
            final java.lang.Object $longitude = this.getLongitude();
            result = result * PRIME + ($longitude == null ? 43 : $longitude.hashCode());
            final java.lang.Object $name = this.getName();
            result = result * PRIME + ($name == null ? 43 : $name.hashCode());
            final java.lang.Object $avatarUrl = this.getAvatarUrl();
            result = result * PRIME + ($avatarUrl == null ? 43 : $avatarUrl.hashCode());
            return result;
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "UserDto.NearbyUserDto(id=" + this.getId() + ", name=" + this.getName() + ", avatarUrl=" + this.getAvatarUrl() + ", latitude=" + this.getLatitude() + ", longitude=" + this.getLongitude() + ", distanceKm=" + this.getDistanceKm() + ")";
        }
    }
}
