// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.entity;

import com.example.demo.enums.BookingStatus;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "bookings", indexes = {@Index(name = "idx_booking_customer", columnList = "customer_id"), @Index(name = "idx_booking_service", columnList = "service_id"), @Index(name = "idx_booking_status", columnList = "status")})
public class Booking {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "service_id", nullable = false)
    private ServiceListing service;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private User customer;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private BookingStatus status = BookingStatus.PENDING;
    @Column(length = 1000)
    private String notes;
    private LocalDateTime scheduledAt;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class BookingBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private ServiceListing service;
        @java.lang.SuppressWarnings("all")
        
        private User customer;
        @java.lang.SuppressWarnings("all")
        
        private BookingStatus status;
        @java.lang.SuppressWarnings("all")
        
        private String notes;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime scheduledAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        
        BookingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Booking.BookingBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Booking.BookingBuilder service(final ServiceListing service) {
            this.service = service;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Booking.BookingBuilder customer(final User customer) {
            this.customer = customer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Booking.BookingBuilder status(final BookingStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Booking.BookingBuilder notes(final String notes) {
            this.notes = notes;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Booking.BookingBuilder scheduledAt(final LocalDateTime scheduledAt) {
            this.scheduledAt = scheduledAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Booking.BookingBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Booking.BookingBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Booking build() {
            return new Booking(this.id, this.service, this.customer, this.status, this.notes, this.scheduledAt, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Booking.BookingBuilder(id=" + this.id + ", service=" + this.service + ", customer=" + this.customer + ", status=" + this.status + ", notes=" + this.notes + ", scheduledAt=" + this.scheduledAt + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Booking.BookingBuilder builder() {
        return new Booking.BookingBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public ServiceListing getService() {
        return this.service;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getCustomer() {
        return this.customer;
    }

    @java.lang.SuppressWarnings("all")
    
    public BookingStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getNotes() {
        return this.notes;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getScheduledAt() {
        return this.scheduledAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setService(final ServiceListing service) {
        this.service = service;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCustomer(final User customer) {
        this.customer = customer;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setStatus(final BookingStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setNotes(final String notes) {
        this.notes = notes;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setScheduledAt(final LocalDateTime scheduledAt) {
        this.scheduledAt = scheduledAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public Booking() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Booking(final Long id, final ServiceListing service, final User customer, final BookingStatus status, final String notes, final LocalDateTime scheduledAt, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.service = service;
        this.customer = customer;
        this.status = status;
        this.notes = notes;
        this.scheduledAt = scheduledAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
