// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "comments", indexes = {@Index(name = "idx_comment_post", columnList = "post_id"), @Index(name = "idx_comment_author", columnList = "author_id")})
public class Comment {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "post_id", nullable = false)
    private Post post;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "author_id", nullable = false)
    private User author;
    @Column(nullable = false, length = 1000)
    private String text;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class CommentBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private Post post;
        @java.lang.SuppressWarnings("all")
        
        private User author;
        @java.lang.SuppressWarnings("all")
        
        private String text;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        CommentBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Comment.CommentBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Comment.CommentBuilder post(final Post post) {
            this.post = post;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Comment.CommentBuilder author(final User author) {
            this.author = author;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Comment.CommentBuilder text(final String text) {
            this.text = text;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Comment.CommentBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Comment build() {
            return new Comment(this.id, this.post, this.author, this.text, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Comment.CommentBuilder(id=" + this.id + ", post=" + this.post + ", author=" + this.author + ", text=" + this.text + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Comment.CommentBuilder builder() {
        return new Comment.CommentBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public Post getPost() {
        return this.post;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getAuthor() {
        return this.author;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getText() {
        return this.text;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPost(final Post post) {
        this.post = post;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setAuthor(final User author) {
        this.author = author;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setText(final String text) {
        this.text = text;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public Comment() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Comment(final Long id, final Post post, final User author, final String text, final LocalDateTime createdAt) {
        this.id = id;
        this.post = post;
        this.author = author;
        this.text = text;
        this.createdAt = createdAt;
    }
}
