// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "conversations")
public class Conversation {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToMany(mappedBy = "conversations", fetch = FetchType.LAZY)
    private Set<User> participants;
    @Column(length = 500)
    private String lastMessage;
    private LocalDateTime lastMessageAt;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    
    private static Set<User> $default$participants() {
        return new HashSet<>();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class ConversationBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private boolean participants$set;
        @java.lang.SuppressWarnings("all")
        
        private Set<User> participants$value;
        @java.lang.SuppressWarnings("all")
        
        private String lastMessage;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime lastMessageAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        ConversationBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Conversation.ConversationBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Conversation.ConversationBuilder participants(final Set<User> participants) {
            this.participants$value = participants;
            participants$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Conversation.ConversationBuilder lastMessage(final String lastMessage) {
            this.lastMessage = lastMessage;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Conversation.ConversationBuilder lastMessageAt(final LocalDateTime lastMessageAt) {
            this.lastMessageAt = lastMessageAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Conversation.ConversationBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Conversation build() {
            Set<User> participants$value = this.participants$value;
            if (!this.participants$set) participants$value = Conversation.$default$participants();
            return new Conversation(this.id, participants$value, this.lastMessage, this.lastMessageAt, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Conversation.ConversationBuilder(id=" + this.id + ", participants$value=" + this.participants$value + ", lastMessage=" + this.lastMessage + ", lastMessageAt=" + this.lastMessageAt + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Conversation.ConversationBuilder builder() {
        return new Conversation.ConversationBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public Set<User> getParticipants() {
        return this.participants;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getLastMessage() {
        return this.lastMessage;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getLastMessageAt() {
        return this.lastMessageAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setParticipants(final Set<User> participants) {
        this.participants = participants;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLastMessage(final String lastMessage) {
        this.lastMessage = lastMessage;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLastMessageAt(final LocalDateTime lastMessageAt) {
        this.lastMessageAt = lastMessageAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public Conversation() {
        this.participants = Conversation.$default$participants();
    }

    @java.lang.SuppressWarnings("all")
    
    public Conversation(final Long id, final Set<User> participants, final String lastMessage, final LocalDateTime lastMessageAt, final LocalDateTime createdAt) {
        this.id = id;
        this.participants = participants;
        this.lastMessage = lastMessage;
        this.lastMessageAt = lastMessageAt;
        this.createdAt = createdAt;
    }
}
