// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "messages", indexes = {@Index(name = "idx_message_conversation", columnList = "conversation_id"), @Index(name = "idx_message_sender", columnList = "sender_id"), @Index(name = "idx_message_created", columnList = "created_at")})
public class Message {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "conversation_id", nullable = false)
    private Conversation conversation;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = false)
    private User sender;
    @Column(nullable = false, length = 4000)
    private String content;
    @Column(nullable = false)
    private boolean read = false;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class MessageBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private Conversation conversation;
        @java.lang.SuppressWarnings("all")
        
        private User sender;
        @java.lang.SuppressWarnings("all")
        
        private String content;
        @java.lang.SuppressWarnings("all")
        
        private boolean read;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        MessageBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Message.MessageBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Message.MessageBuilder conversation(final Conversation conversation) {
            this.conversation = conversation;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Message.MessageBuilder sender(final User sender) {
            this.sender = sender;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Message.MessageBuilder content(final String content) {
            this.content = content;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Message.MessageBuilder read(final boolean read) {
            this.read = read;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Message.MessageBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Message build() {
            return new Message(this.id, this.conversation, this.sender, this.content, this.read, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Message.MessageBuilder(id=" + this.id + ", conversation=" + this.conversation + ", sender=" + this.sender + ", content=" + this.content + ", read=" + this.read + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Message.MessageBuilder builder() {
        return new Message.MessageBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public Conversation getConversation() {
        return this.conversation;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getSender() {
        return this.sender;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    
    public boolean isRead() {
        return this.read;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setConversation(final Conversation conversation) {
        this.conversation = conversation;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setSender(final User sender) {
        this.sender = sender;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRead(final boolean read) {
        this.read = read;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public Message() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Message(final Long id, final Conversation conversation, final User sender, final String content, final boolean read, final LocalDateTime createdAt) {
        this.id = id;
        this.conversation = conversation;
        this.sender = sender;
        this.content = content;
        this.read = read;
        this.createdAt = createdAt;
    }
}
