// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.entity;

import com.example.demo.enums.NotificationType;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "notifications", indexes = {@Index(name = "idx_notif_recipient", columnList = "recipient_id"), @Index(name = "idx_notif_read", columnList = "read"), @Index(name = "idx_notif_created", columnList = "created_at")})
public class Notification {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "recipient_id", nullable = false)
    private User recipient;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationType type;
    @Column(nullable = false)
    private String title;
    @Column(nullable = false, length = 500)
    private String body;
    private Long referenceId; // post id, booking id, alert id, etc.
    @Column(nullable = false)
    private boolean read = false;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class NotificationBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private User recipient;
        @java.lang.SuppressWarnings("all")
        
        private NotificationType type;
        @java.lang.SuppressWarnings("all")
        
        private String title;
        @java.lang.SuppressWarnings("all")
        
        private String body;
        @java.lang.SuppressWarnings("all")
        
        private Long referenceId;
        @java.lang.SuppressWarnings("all")
        
        private boolean read;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        NotificationBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Notification.NotificationBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Notification.NotificationBuilder recipient(final User recipient) {
            this.recipient = recipient;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Notification.NotificationBuilder type(final NotificationType type) {
            this.type = type;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Notification.NotificationBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Notification.NotificationBuilder body(final String body) {
            this.body = body;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Notification.NotificationBuilder referenceId(final Long referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Notification.NotificationBuilder read(final boolean read) {
            this.read = read;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Notification.NotificationBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Notification build() {
            return new Notification(this.id, this.recipient, this.type, this.title, this.body, this.referenceId, this.read, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Notification.NotificationBuilder(id=" + this.id + ", recipient=" + this.recipient + ", type=" + this.type + ", title=" + this.title + ", body=" + this.body + ", referenceId=" + this.referenceId + ", read=" + this.read + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Notification.NotificationBuilder builder() {
        return new Notification.NotificationBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getRecipient() {
        return this.recipient;
    }

    @java.lang.SuppressWarnings("all")
    
    public NotificationType getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getBody() {
        return this.body;
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getReferenceId() {
        return this.referenceId;
    }

    @java.lang.SuppressWarnings("all")
    
    public boolean isRead() {
        return this.read;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRecipient(final User recipient) {
        this.recipient = recipient;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setType(final NotificationType type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setBody(final String body) {
        this.body = body;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setReferenceId(final Long referenceId) {
        this.referenceId = referenceId;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRead(final boolean read) {
        this.read = read;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public Notification() {
    }

    @java.lang.SuppressWarnings("all")
    
    public Notification(final Long id, final User recipient, final NotificationType type, final String title, final String body, final Long referenceId, final boolean read, final LocalDateTime createdAt) {
        this.id = id;
        this.recipient = recipient;
        this.type = type;
        this.title = title;
        this.body = body;
        this.referenceId = referenceId;
        this.read = read;
        this.createdAt = createdAt;
    }
}
