// Generated by delombok at Thu Mar 12 15:04:28 IST 2026
package com.example.demo.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "otp_tokens", indexes = {@Index(name = "idx_otp_email", columnList = "email")})
public class OtpToken {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String email;
    @Column(nullable = false, length = 6)
    private String code;
    @Column(nullable = false)
    private LocalDateTime expiresAt;
    @Column(nullable = false)
    private boolean used = false;
    private int attempts = 0;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }

    public boolean isExpired() {
        return LocalDateTime.now().isAfter(expiresAt);
    }


    @java.lang.SuppressWarnings("all")
    
    public static class OtpTokenBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private String email;
        @java.lang.SuppressWarnings("all")
        
        private String code;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime expiresAt;
        @java.lang.SuppressWarnings("all")
        
        private boolean used;
        @java.lang.SuppressWarnings("all")
        
        private int attempts;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;

        @java.lang.SuppressWarnings("all")
        
        OtpTokenBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OtpToken.OtpTokenBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OtpToken.OtpTokenBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OtpToken.OtpTokenBuilder code(final String code) {
            this.code = code;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OtpToken.OtpTokenBuilder expiresAt(final LocalDateTime expiresAt) {
            this.expiresAt = expiresAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OtpToken.OtpTokenBuilder used(final boolean used) {
            this.used = used;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OtpToken.OtpTokenBuilder attempts(final int attempts) {
            this.attempts = attempts;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public OtpToken.OtpTokenBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public OtpToken build() {
            return new OtpToken(this.id, this.email, this.code, this.expiresAt, this.used, this.attempts, this.createdAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "OtpToken.OtpTokenBuilder(id=" + this.id + ", email=" + this.email + ", code=" + this.code + ", expiresAt=" + this.expiresAt + ", used=" + this.used + ", attempts=" + this.attempts + ", createdAt=" + this.createdAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static OtpToken.OtpTokenBuilder builder() {
        return new OtpToken.OtpTokenBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getCode() {
        return this.code;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getExpiresAt() {
        return this.expiresAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public boolean isUsed() {
        return this.used;
    }

    @java.lang.SuppressWarnings("all")
    
    public int getAttempts() {
        return this.attempts;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCode(final String code) {
        this.code = code;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setExpiresAt(final LocalDateTime expiresAt) {
        this.expiresAt = expiresAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUsed(final boolean used) {
        this.used = used;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setAttempts(final int attempts) {
        this.attempts = attempts;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public OtpToken() {
    }

    @java.lang.SuppressWarnings("all")
    
    public OtpToken(final Long id, final String email, final String code, final LocalDateTime expiresAt, final boolean used, final int attempts, final LocalDateTime createdAt) {
        this.id = id;
        this.email = email;
        this.code = code;
        this.expiresAt = expiresAt;
        this.used = used;
        this.attempts = attempts;
        this.createdAt = createdAt;
    }
}
