// Generated by delombok at Thu Mar 12 15:04:29 IST 2026
package com.example.demo.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

@Entity
@Table(name = "posts", indexes = {@Index(name = "idx_post_author", columnList = "author_id"), @Index(name = "idx_post_location", columnList = "latitude, longitude"), @Index(name = "idx_post_created", columnList = "created_at")})
public class Post {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "author_id", nullable = false)
    private User author;
    @Column(nullable = false, length = 2000)
    private String content;
    private String imageUrl;
    private Double latitude;
    private Double longitude;
    @Column(nullable = false)
    private int likeCount = 0;
    @Column(nullable = false)
    private int commentCount = 0;
    @OneToMany(mappedBy = "post", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Comment> comments;
    @OneToMany(mappedBy = "post", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<PostLike> likes;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    @java.lang.SuppressWarnings("all")
    
    private static List<Comment> $default$comments() {
        return new ArrayList<>();
    }

    @java.lang.SuppressWarnings("all")
    
    private static List<PostLike> $default$likes() {
        return new ArrayList<>();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class PostBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private User author;
        @java.lang.SuppressWarnings("all")
        
        private String content;
        @java.lang.SuppressWarnings("all")
        
        private String imageUrl;
        @java.lang.SuppressWarnings("all")
        
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        
        private int likeCount;
        @java.lang.SuppressWarnings("all")
        
        private int commentCount;
        @java.lang.SuppressWarnings("all")
        
        private boolean comments$set;
        @java.lang.SuppressWarnings("all")
        
        private List<Comment> comments$value;
        @java.lang.SuppressWarnings("all")
        
        private boolean likes$set;
        @java.lang.SuppressWarnings("all")
        
        private List<PostLike> likes$value;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        
        PostBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder author(final User author) {
            this.author = author;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder content(final String content) {
            this.content = content;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder imageUrl(final String imageUrl) {
            this.imageUrl = imageUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder likeCount(final int likeCount) {
            this.likeCount = likeCount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder commentCount(final int commentCount) {
            this.commentCount = commentCount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder comments(final List<Comment> comments) {
            this.comments$value = comments;
            comments$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder likes(final List<PostLike> likes) {
            this.likes$value = likes;
            likes$set = true;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public Post.PostBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public Post build() {
            List<Comment> comments$value = this.comments$value;
            if (!this.comments$set) comments$value = Post.$default$comments();
            List<PostLike> likes$value = this.likes$value;
            if (!this.likes$set) likes$value = Post.$default$likes();
            return new Post(this.id, this.author, this.content, this.imageUrl, this.latitude, this.longitude, this.likeCount, this.commentCount, comments$value, likes$value, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "Post.PostBuilder(id=" + this.id + ", author=" + this.author + ", content=" + this.content + ", imageUrl=" + this.imageUrl + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", likeCount=" + this.likeCount + ", commentCount=" + this.commentCount + ", comments$value=" + this.comments$value + ", likes$value=" + this.likes$value + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static Post.PostBuilder builder() {
        return new Post.PostBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getAuthor() {
        return this.author;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getContent() {
        return this.content;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getImageUrl() {
        return this.imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public int getLikeCount() {
        return this.likeCount;
    }

    @java.lang.SuppressWarnings("all")
    
    public int getCommentCount() {
        return this.commentCount;
    }

    @java.lang.SuppressWarnings("all")
    
    public List<Comment> getComments() {
        return this.comments;
    }

    @java.lang.SuppressWarnings("all")
    
    public List<PostLike> getLikes() {
        return this.likes;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setAuthor(final User author) {
        this.author = author;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setContent(final String content) {
        this.content = content;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setImageUrl(final String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLikeCount(final int likeCount) {
        this.likeCount = likeCount;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCommentCount(final int commentCount) {
        this.commentCount = commentCount;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setComments(final List<Comment> comments) {
        this.comments = comments;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLikes(final List<PostLike> likes) {
        this.likes = likes;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public Post() {
        this.comments = Post.$default$comments();
        this.likes = Post.$default$likes();
    }

    @java.lang.SuppressWarnings("all")
    
    public Post(final Long id, final User author, final String content, final String imageUrl, final Double latitude, final Double longitude, final int likeCount, final int commentCount, final List<Comment> comments, final List<PostLike> likes, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.author = author;
        this.content = content;
        this.imageUrl = imageUrl;
        this.latitude = latitude;
        this.longitude = longitude;
        this.likeCount = likeCount;
        this.commentCount = commentCount;
        this.comments = comments;
        this.likes = likes;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
