// Generated by delombok at Thu Mar 12 15:04:29 IST 2026
package com.example.demo.entity;

import com.example.demo.enums.ServiceCategory;
import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "service_listings", indexes = {@Index(name = "idx_service_provider", columnList = "provider_id"), @Index(name = "idx_service_category", columnList = "category"), @Index(name = "idx_service_location", columnList = "latitude, longitude")})
public class ServiceListing {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "provider_id", nullable = false)
    private User provider;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private ServiceCategory category;
    @Column(nullable = false)
    private String title;
    @Column(length = 2000)
    private String description;
    @Column(nullable = false, precision = 10, scale = 2)
    private BigDecimal price;
    private String priceUnit; // per hour, per visit, etc.
    @Column(nullable = false)
    private double rating = 0.0;
    @Column(nullable = false)
    private int ratingCount = 0;
    private Double latitude;
    private Double longitude;
    private boolean active = true;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class ServiceListingBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private User provider;
        @java.lang.SuppressWarnings("all")
        
        private ServiceCategory category;
        @java.lang.SuppressWarnings("all")
        
        private String title;
        @java.lang.SuppressWarnings("all")
        
        private String description;
        @java.lang.SuppressWarnings("all")
        
        private BigDecimal price;
        @java.lang.SuppressWarnings("all")
        
        private String priceUnit;
        @java.lang.SuppressWarnings("all")
        
        private double rating;
        @java.lang.SuppressWarnings("all")
        
        private int ratingCount;
        @java.lang.SuppressWarnings("all")
        
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        
        private boolean active;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime updatedAt;

        @java.lang.SuppressWarnings("all")
        
        ServiceListingBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder provider(final User provider) {
            this.provider = provider;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder category(final ServiceCategory category) {
            this.category = category;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder title(final String title) {
            this.title = title;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder description(final String description) {
            this.description = description;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder price(final BigDecimal price) {
            this.price = price;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder priceUnit(final String priceUnit) {
            this.priceUnit = priceUnit;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder rating(final double rating) {
            this.rating = rating;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder ratingCount(final int ratingCount) {
            this.ratingCount = ratingCount;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder active(final boolean active) {
            this.active = active;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public ServiceListing.ServiceListingBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public ServiceListing build() {
            return new ServiceListing(this.id, this.provider, this.category, this.title, this.description, this.price, this.priceUnit, this.rating, this.ratingCount, this.latitude, this.longitude, this.active, this.createdAt, this.updatedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "ServiceListing.ServiceListingBuilder(id=" + this.id + ", provider=" + this.provider + ", category=" + this.category + ", title=" + this.title + ", description=" + this.description + ", price=" + this.price + ", priceUnit=" + this.priceUnit + ", rating=" + this.rating + ", ratingCount=" + this.ratingCount + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", active=" + this.active + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static ServiceListing.ServiceListingBuilder builder() {
        return new ServiceListing.ServiceListingBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getProvider() {
        return this.provider;
    }

    @java.lang.SuppressWarnings("all")
    
    public ServiceCategory getCategory() {
        return this.category;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getTitle() {
        return this.title;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getDescription() {
        return this.description;
    }

    @java.lang.SuppressWarnings("all")
    
    public BigDecimal getPrice() {
        return this.price;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getPriceUnit() {
        return this.priceUnit;
    }

    @java.lang.SuppressWarnings("all")
    
    public double getRating() {
        return this.rating;
    }

    @java.lang.SuppressWarnings("all")
    
    public int getRatingCount() {
        return this.ratingCount;
    }

    @java.lang.SuppressWarnings("all")
    
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public boolean isActive() {
        return this.active;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setProvider(final User provider) {
        this.provider = provider;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCategory(final ServiceCategory category) {
        this.category = category;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setTitle(final String title) {
        this.title = title;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setDescription(final String description) {
        this.description = description;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPrice(final BigDecimal price) {
        this.price = price;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPriceUnit(final String priceUnit) {
        this.priceUnit = priceUnit;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRating(final double rating) {
        this.rating = rating;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRatingCount(final int ratingCount) {
        this.ratingCount = ratingCount;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setActive(final boolean active) {
        this.active = active;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public ServiceListing() {
    }

    @java.lang.SuppressWarnings("all")
    
    public ServiceListing(final Long id, final User provider, final ServiceCategory category, final String title, final String description, final BigDecimal price, final String priceUnit, final double rating, final int ratingCount, final Double latitude, final Double longitude, final boolean active, final LocalDateTime createdAt, final LocalDateTime updatedAt) {
        this.id = id;
        this.provider = provider;
        this.category = category;
        this.title = title;
        this.description = description;
        this.price = price;
        this.priceUnit = priceUnit;
        this.rating = rating;
        this.ratingCount = ratingCount;
        this.latitude = latitude;
        this.longitude = longitude;
        this.active = active;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }
}
