// Generated by delombok at Thu Mar 12 15:04:29 IST 2026
package com.example.demo.entity;

import com.example.demo.enums.AlertStatus;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(name = "sos_alerts", indexes = {@Index(name = "idx_sos_user", columnList = "user_id"), @Index(name = "idx_sos_status", columnList = "status"), @Index(name = "idx_sos_created", columnList = "created_at")})
public class SosAlert {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;
    @Column(nullable = false)
    private Double latitude;
    @Column(nullable = false)
    private Double longitude;
    @Column(length = 500)
    private String message;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertStatus status = AlertStatus.ACTIVE;
    private int nearbyUsersNotified = 0;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    private LocalDateTime resolvedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class SosAlertBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private User user;
        @java.lang.SuppressWarnings("all")
        
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        
        private String message;
        @java.lang.SuppressWarnings("all")
        
        private AlertStatus status;
        @java.lang.SuppressWarnings("all")
        
        private int nearbyUsersNotified;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime resolvedAt;

        @java.lang.SuppressWarnings("all")
        
        SosAlertBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder user(final User user) {
            this.user = user;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder message(final String message) {
            this.message = message;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder status(final AlertStatus status) {
            this.status = status;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder nearbyUsersNotified(final int nearbyUsersNotified) {
            this.nearbyUsersNotified = nearbyUsersNotified;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public SosAlert.SosAlertBuilder resolvedAt(final LocalDateTime resolvedAt) {
            this.resolvedAt = resolvedAt;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public SosAlert build() {
            return new SosAlert(this.id, this.user, this.latitude, this.longitude, this.message, this.status, this.nearbyUsersNotified, this.createdAt, this.resolvedAt);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "SosAlert.SosAlertBuilder(id=" + this.id + ", user=" + this.user + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", message=" + this.message + ", status=" + this.status + ", nearbyUsersNotified=" + this.nearbyUsersNotified + ", createdAt=" + this.createdAt + ", resolvedAt=" + this.resolvedAt + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static SosAlert.SosAlertBuilder builder() {
        return new SosAlert.SosAlertBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public User getUser() {
        return this.user;
    }

    @java.lang.SuppressWarnings("all")
    
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getMessage() {
        return this.message;
    }

    @java.lang.SuppressWarnings("all")
    
    public AlertStatus getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    
    public int getNearbyUsersNotified() {
        return this.nearbyUsersNotified;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getResolvedAt() {
        return this.resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUser(final User user) {
        this.user = user;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setMessage(final String message) {
        this.message = message;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setStatus(final AlertStatus status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setNearbyUsersNotified(final int nearbyUsersNotified) {
        this.nearbyUsersNotified = nearbyUsersNotified;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setResolvedAt(final LocalDateTime resolvedAt) {
        this.resolvedAt = resolvedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public SosAlert() {
    }

    @java.lang.SuppressWarnings("all")
    
    public SosAlert(final Long id, final User user, final Double latitude, final Double longitude, final String message, final AlertStatus status, final int nearbyUsersNotified, final LocalDateTime createdAt, final LocalDateTime resolvedAt) {
        this.id = id;
        this.user = user;
        this.latitude = latitude;
        this.longitude = longitude;
        this.message = message;
        this.status = status;
        this.nearbyUsersNotified = nearbyUsersNotified;
        this.createdAt = createdAt;
        this.resolvedAt = resolvedAt;
    }
}
