// Generated by delombok at Thu Mar 12 15:04:29 IST 2026
package com.example.demo.entity;

import com.example.demo.enums.Role;
import jakarta.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

@Entity
@Table(name = "users", indexes = {@Index(name = "idx_user_email", columnList = "email"), @Index(name = "idx_user_location", columnList = "latitude, longitude")})
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(nullable = false)
    private String name;
    @Column(unique = true, nullable = false)
    private String email;
    private String phone;
    private String avatarUrl;
    @Column(length = 500)
    private String bio;
    private Double latitude;
    private Double longitude;
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private Role role = Role.USER;
    @Column(nullable = false)
    private boolean verified = false;
    private LocalDateTime locationUpdatedAt;
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    @ManyToMany(fetch = FetchType.LAZY)
    @JoinTable(name = "conversation_participants", joinColumns = @JoinColumn(name = "user_id"), inverseJoinColumns = @JoinColumn(name = "conversation_id"))
    private Set<Conversation> conversations = new HashSet<>();

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }


    @java.lang.SuppressWarnings("all")
    
    public static class UserBuilder {
        @java.lang.SuppressWarnings("all")
        
        private Long id;
        @java.lang.SuppressWarnings("all")
        
        private String name;
        @java.lang.SuppressWarnings("all")
        
        private String email;
        @java.lang.SuppressWarnings("all")
        
        private String phone;
        @java.lang.SuppressWarnings("all")
        
        private String avatarUrl;
        @java.lang.SuppressWarnings("all")
        
        private String bio;
        @java.lang.SuppressWarnings("all")
        
        private Double latitude;
        @java.lang.SuppressWarnings("all")
        
        private Double longitude;
        @java.lang.SuppressWarnings("all")
        
        private Role role;
        @java.lang.SuppressWarnings("all")
        
        private boolean verified;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime locationUpdatedAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime createdAt;
        @java.lang.SuppressWarnings("all")
        
        private LocalDateTime updatedAt;
        @java.lang.SuppressWarnings("all")
        
        private Set<Conversation> conversations;

        @java.lang.SuppressWarnings("all")
        
        UserBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder name(final String name) {
            this.name = name;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder email(final String email) {
            this.email = email;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder phone(final String phone) {
            this.phone = phone;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder avatarUrl(final String avatarUrl) {
            this.avatarUrl = avatarUrl;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder bio(final String bio) {
            this.bio = bio;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder latitude(final Double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder longitude(final Double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder role(final Role role) {
            this.role = role;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder verified(final boolean verified) {
            this.verified = verified;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder locationUpdatedAt(final LocalDateTime locationUpdatedAt) {
            this.locationUpdatedAt = locationUpdatedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder createdAt(final LocalDateTime createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder updatedAt(final LocalDateTime updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        
        public User.UserBuilder conversations(final Set<Conversation> conversations) {
            this.conversations = conversations;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        
        public User build() {
            return new User(this.id, this.name, this.email, this.phone, this.avatarUrl, this.bio, this.latitude, this.longitude, this.role, this.verified, this.locationUpdatedAt, this.createdAt, this.updatedAt, this.conversations);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        
        public java.lang.String toString() {
            return "User.UserBuilder(id=" + this.id + ", name=" + this.name + ", email=" + this.email + ", phone=" + this.phone + ", avatarUrl=" + this.avatarUrl + ", bio=" + this.bio + ", latitude=" + this.latitude + ", longitude=" + this.longitude + ", role=" + this.role + ", verified=" + this.verified + ", locationUpdatedAt=" + this.locationUpdatedAt + ", createdAt=" + this.createdAt + ", updatedAt=" + this.updatedAt + ", conversations=" + this.conversations + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    
    public static User.UserBuilder builder() {
        return new User.UserBuilder();
    }

    @java.lang.SuppressWarnings("all")
    
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getEmail() {
        return this.email;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getPhone() {
        return this.phone;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getAvatarUrl() {
        return this.avatarUrl;
    }

    @java.lang.SuppressWarnings("all")
    
    public String getBio() {
        return this.bio;
    }

    @java.lang.SuppressWarnings("all")
    
    public Double getLatitude() {
        return this.latitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public Double getLongitude() {
        return this.longitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public Role getRole() {
        return this.role;
    }

    @java.lang.SuppressWarnings("all")
    
    public boolean isVerified() {
        return this.verified;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getLocationUpdatedAt() {
        return this.locationUpdatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public Set<Conversation> getConversations() {
        return this.conversations;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setEmail(final String email) {
        this.email = email;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setPhone(final String phone) {
        this.phone = phone;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setAvatarUrl(final String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setBio(final String bio) {
        this.bio = bio;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLatitude(final Double latitude) {
        this.latitude = latitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLongitude(final Double longitude) {
        this.longitude = longitude;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setRole(final Role role) {
        this.role = role;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setVerified(final boolean verified) {
        this.verified = verified;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setLocationUpdatedAt(final LocalDateTime locationUpdatedAt) {
        this.locationUpdatedAt = locationUpdatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setCreatedAt(final LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setUpdatedAt(final LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @java.lang.SuppressWarnings("all")
    
    public void setConversations(final Set<Conversation> conversations) {
        this.conversations = conversations;
    }

    @java.lang.SuppressWarnings("all")
    
    public User() {
    }

    @java.lang.SuppressWarnings("all")
    
    public User(final Long id, final String name, final String email, final String phone, final String avatarUrl, final String bio, final Double latitude, final Double longitude, final Role role, final boolean verified, final LocalDateTime locationUpdatedAt, final LocalDateTime createdAt, final LocalDateTime updatedAt, final Set<Conversation> conversations) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.phone = phone;
        this.avatarUrl = avatarUrl;
        this.bio = bio;
        this.latitude = latitude;
        this.longitude = longitude;
        this.role = role;
        this.verified = verified;
        this.locationUpdatedAt = locationUpdatedAt;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.conversations = conversations;
    }
}
