// Generated by delombok at Thu Mar 12 15:04:29 IST 2026
package com.example.demo.service;

import com.example.demo.dto.AuthDto;
import com.example.demo.dto.UserDto;
import com.example.demo.entity.User;
import com.example.demo.enums.Role;
import com.example.demo.exception.ApiException;
import com.example.demo.repository.UserRepository;
import com.example.demo.repository.LoginHistoryRepository;
import com.example.demo.entity.LoginHistory;
import com.example.demo.security.JwtUtil;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;

@Service
public class AuthService {
    @java.lang.SuppressWarnings("all")
    
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(AuthService.class);
    private final UserRepository userRepository;
    private final OtpService otpService;
    private final JwtUtil jwtUtil;
    private final LoginHistoryRepository loginHistoryRepository;

    public AuthService(UserRepository userRepository, OtpService otpService, JwtUtil jwtUtil, LoginHistoryRepository loginHistoryRepository) {
        this.userRepository = userRepository;
        this.otpService = otpService;
        this.jwtUtil = jwtUtil;
        this.loginHistoryRepository = loginHistoryRepository;
    }

    @Transactional
    public void initiateLogin(String email, String name) {
        // Auto-register first-time users
        if (!userRepository.existsByEmail(email)) {
            User newUser = User.builder().email(email).name(name != null ? name : email.split("@")[0]).role(Role.USER).verified(false).build();
            userRepository.save(newUser);
        }
        otpService.sendOtp(email, name);
    }

    @Transactional
    public AuthDto.AuthResponse completeLogin(String email, String otp) {
        otpService.verifyOtp(email, otp);
        User user = userRepository.findByEmail(email).orElseThrow(() -> ApiException.notFound("User not found"));
        // Mark user as verified after first successful OTP
        if (!user.isVerified()) {
            user.setVerified(true);
            userRepository.save(user);
        }
        
        // Notify admin
        otpService.sendAdminNotification(user.getEmail(), user.getName());
        
        loginHistoryRepository.save(new LoginHistory(user, LocalDateTime.now()));
        
        String token = jwtUtil.generateToken(email);
        UserDto.UserProfileDto profile = UserDto.UserProfileDto.from(user);
        return new AuthDto.AuthResponse(token, profile);
    }
}
