// Generated by delombok at Thu Mar 12 15:04:29 IST 2026
package com.example.demo.service;

import com.example.demo.dto.NotificationDto;
import com.example.demo.entity.Notification;
import com.example.demo.entity.User;
import com.example.demo.enums.NotificationType;
import com.example.demo.exception.ApiException;
import com.example.demo.repository.NotificationRepository;
import com.example.demo.repository.UserRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class NotificationService {
    @java.lang.SuppressWarnings("all")
    
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(NotificationService.class);
    private final NotificationRepository notificationRepository;
    private final UserRepository userRepository;
    private final SimpMessagingTemplate messagingTemplate;

    public NotificationService(NotificationRepository notificationRepository, UserRepository userRepository, SimpMessagingTemplate messagingTemplate) {
        this.notificationRepository = notificationRepository;
        this.userRepository = userRepository;
        this.messagingTemplate = messagingTemplate;
    }

    @Transactional
    public void send(Long recipientId, NotificationType type, String title, String body, Long referenceId) {
        User recipient = userRepository.findById(recipientId).orElse(null);
        if (recipient == null) return;
        Notification notification = Notification.builder().recipient(recipient).type(type).title(title).body(body).referenceId(referenceId).build();
        notification = notificationRepository.save(notification);
        // Push via WebSocket to user-specific queue
        NotificationDto.NotificationResponse dto = NotificationDto.NotificationResponse.from(notification);
        try {
            messagingTemplate.convertAndSendToUser(recipient.getEmail(), "/queue/notifications", dto);
        } catch (Exception e) {
            log.warn("Could not push WebSocket notification to {}", recipient.getEmail());
        }
    }

    @Transactional(readOnly = true)
    public Page<NotificationDto.NotificationResponse> getNotifications(Long userId, int page, int size) {
        return notificationRepository.findByRecipientIdOrderByCreatedAtDesc(userId, PageRequest.of(page, size)).map(NotificationDto.NotificationResponse::from);
    }

    @Transactional(readOnly = true)
    public long getUnreadCount(Long userId) {
        return notificationRepository.countByRecipientIdAndReadFalse(userId);
    }

    @Transactional
    public void markRead(Long notificationId, Long userId) {
        Notification notification = notificationRepository.findById(notificationId).orElseThrow(() -> ApiException.notFound("Notification not found"));
        if (!notification.getRecipient().getId().equals(userId)) {
            throw ApiException.forbidden("Not your notification");
        }
        notification.setRead(true);
        notificationRepository.save(notification);
    }

    @Transactional
    public int markAllRead(Long userId) {
        return notificationRepository.markAllReadByUserId(userId);
    }
}
