// Generated by delombok at Thu Mar 12 15:04:29 IST 2026
package com.example.demo.service;

import com.example.demo.entity.OtpToken;
import com.example.demo.entity.User;
import com.example.demo.exception.ApiException;
import com.example.demo.repository.OtpTokenRepository;
import com.example.demo.repository.UserRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.security.SecureRandom;
import java.time.LocalDateTime;

@Service
public class OtpService {
    @java.lang.SuppressWarnings("all")
    
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(OtpService.class);
    private final OtpTokenRepository otpTokenRepository;
    private final UserRepository userRepository;
    private final JavaMailSender mailSender;

    public OtpService(OtpTokenRepository otpTokenRepository, UserRepository userRepository, JavaMailSender mailSender) {
        this.otpTokenRepository = otpTokenRepository;
        this.userRepository = userRepository;
        this.mailSender = mailSender;
    }

    @Value("${app.otp.expiry-minutes:5}")
    private int otpExpiryMinutes;
    @Value("${app.otp.max-attempts:5}")
    private int maxAttempts;
    @Value("${app.mail.from}")
    private String mailFrom;
    private static final SecureRandom RANDOM = new SecureRandom();

    @Transactional
    public void sendOtp(String email, String name) {
        // Invalidate any active OTPs first
        otpTokenRepository.invalidateAllForEmail(email);
        String code = generateCode();
        OtpToken token = OtpToken.builder().email(email).code(code).expiresAt(LocalDateTime.now().plusMinutes(otpExpiryMinutes)).used(false).build();
        otpTokenRepository.save(token);
        sendEmail(email, name, code);
        
        // Output very clearly for local testing without an SMTP server
        log.info("==================================================");
        log.info(" 🔐 LOCAL TEST MODE - OTP for {} is: {} ", email, code);
        log.info("==================================================");
    }

    @Transactional
    public boolean verifyOtp(String email, String code) {
        OtpToken token = otpTokenRepository.findTopByEmailAndUsedFalseOrderByCreatedAtDesc(email).orElseThrow(() -> ApiException.badRequest("No active OTP found. Please request a new one."));
        if (token.isExpired()) {
            throw ApiException.badRequest("OTP has expired. Please request a new one.");
        }
        token.setAttempts(token.getAttempts() + 1);
        if (token.getAttempts() > maxAttempts) {
            token.setUsed(true);
            otpTokenRepository.save(token);
            throw ApiException.badRequest("Too many attempts. Please request a new OTP.");
        }
        if (!token.getCode().equals(code)) {
            otpTokenRepository.save(token);
            throw ApiException.badRequest("Invalid OTP. Please try again.");
        }
        token.setUsed(true);
        otpTokenRepository.save(token);
        return true;
    }

    private String generateCode() {
        return String.format("%06d", RANDOM.nextInt(1000000));
    }

    private void sendEmail(String email, String name, String code) {
        try {
            SimpleMailMessage msg = new SimpleMailMessage();
            msg.setFrom(mailFrom);
            msg.setTo(email);
            msg.setSubject("LocalConnect – Your Login OTP");
            msg.setText("Hi " + (name != null ? name : "there") + ",\n\n" + "Your LocalConnect verification code is:\n\n" + "  " + code + "\n\n" + "This code expires in " + otpExpiryMinutes + " minutes.\n" + "If you did not request this, please ignore this email.\n\n" + "– The LocalConnect Team");
            mailSender.send(msg);
        } catch (Exception e) {
            log.warn("SMTP config missing. Check console for OTP. Error: {}", e.getMessage());
        }
        // Don't throw — OTP is still stored; frontend can retry
    }

    public void sendAdminNotification(String userEmail, String userName) {
        String adminEmail = "admin@localconnect.com";
        try {
            SimpleMailMessage msg = new SimpleMailMessage();
            msg.setFrom(mailFrom);
            msg.setTo(adminEmail);
            msg.setSubject("LocalConnect - New User Login Alert 🚨");
            msg.setText("Admin Alert:\n\nA user just logged in to LocalConnect.\n\nName: " + userName + "\nEmail: " + userEmail + "\nTime: " + LocalDateTime.now());
            mailSender.send(msg);
        } catch (Exception e) {
            log.warn("SMTP config missing for Admin Notification: {}", e.getMessage());
        }
        
        // Always log prominently
        log.info("==================================================");
        log.info(" 🚨 ADMIN ALERT: User {} ({}) just logged in!", userName, userEmail);
        log.info("==================================================");
    }
}
