// Generated by delombok at Thu Mar 12 15:04:29 IST 2026
package com.example.demo.service;

import com.example.demo.dto.SosDto;
import com.example.demo.entity.SosAlert;
import com.example.demo.entity.User;
import com.example.demo.enums.AlertStatus;
import com.example.demo.enums.NotificationType;
import com.example.demo.exception.ApiException;
import com.example.demo.repository.SosAlertRepository;
import com.example.demo.repository.UserRepository;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDateTime;
import java.util.List;

@Service
public class SosAlertService {
    @java.lang.SuppressWarnings("all")
    
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(SosAlertService.class);
    private final SosAlertRepository sosAlertRepository;
    private final UserRepository userRepository;
    private final UserService userService;
    private final NotificationService notificationService;
    private final SimpMessagingTemplate messagingTemplate;

    public SosAlertService(SosAlertRepository sosAlertRepository, UserRepository userRepository, UserService userService, NotificationService notificationService, SimpMessagingTemplate messagingTemplate) {
        this.sosAlertRepository = sosAlertRepository;
        this.userRepository = userRepository;
        this.userService = userService;
        this.notificationService = notificationService;
        this.messagingTemplate = messagingTemplate;
    }

    @Value("${app.sos.default-radius-km:1.0}")
    private double sosRadiusKm;

    @Transactional
    public SosDto.SosAlertResponse triggerSos(SosDto.SosAlertRequest req) {
        User user = userService.currentUser();
        SosAlert alert = SosAlert.builder().user(user).latitude(req.getLatitude()).longitude(req.getLongitude()).message(req.getMessage()).status(AlertStatus.ACTIVE).build();
        alert = sosAlertRepository.save(alert);
        // Find nearby users using Haversine query
        List<User> nearby = userRepository.findNearbyUsers(user.getId(), req.getLatitude(), req.getLongitude(), sosRadiusKm);
        SosDto.SosAlertResponse alertDto = SosDto.SosAlertResponse.from(alert);
        // Broadcast to /topic/sos WebSocket channel
        messagingTemplate.convertAndSend("/topic/sos", alertDto);
        // Notify each nearby user individually
        for (User neighbor : nearby) {
            notificationService.send(neighbor.getId(), NotificationType.SOS_ALERT, "\ud83d\udea8 SOS Alert from " + user.getName(), req.getMessage() != null ? req.getMessage() : "Emergency nearby!", alert.getId());
        }
        alert.setNearbyUsersNotified(nearby.size());
        sosAlertRepository.save(alert);
        alertDto.setNearbyUsersNotified(nearby.size());
        log.info("SOS triggered by user {} — notified {} nearby users", user.getId(), nearby.size());
        return alertDto;
    }

    @Transactional
    public SosDto.SosAlertResponse resolveAlert(Long alertId) {
        User me = userService.currentUser();
        SosAlert alert = sosAlertRepository.findById(alertId).orElseThrow(() -> ApiException.notFound("Alert not found"));
        if (!alert.getUser().getId().equals(me.getId())) {
            throw ApiException.forbidden("You can only resolve your own alerts");
        }
        alert.setStatus(AlertStatus.RESOLVED);
        alert.setResolvedAt(LocalDateTime.now());
        return SosDto.SosAlertResponse.from(sosAlertRepository.save(alert));
    }

    @Transactional(readOnly = true)
    public Page<SosDto.SosAlertResponse> getHistory(int page, int size) {
        User me = userService.currentUser();
        return sosAlertRepository.findByUserIdOrderByCreatedAtDesc(me.getId(), PageRequest.of(page, size)).map(SosDto.SosAlertResponse::from);
    }

    @Transactional(readOnly = true)
    public Page<SosDto.SosAlertResponse> getActiveAlerts(int page, int size) {
        return sosAlertRepository.findAllByOrderByCreatedAtDesc(PageRequest.of(page, size)).map(SosDto.SosAlertResponse::from);
    }
}
